### ISSUE TITLE
Instructor Insights: update layout and section styling 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-course-hugo-theme#9]
#### Designs and Mockups

Before: https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-034-artificial-intelligence-fall-2010/instructor-insights/

After: https://projects.invisionapp.com/d/main?origin=v7#/console/18609637/441780346/preview?scrollOffset=9

#### Acceptance Criteria:

- [x] Section title is "Instructor Insights" not "This Course at MIT" 
- [x] Contents of each section are stacked vertically instead of (occasionally) being multi-column

#### Related Issues

- In the example above, the content is not available in the parsed json, so this issue is blocked by https://github.com/mitodl/ocw-data-parser/issues/21
- instructor quote styling, https://github.com/mitodl/ocw-course-hugo-theme/issues/10
- javascript rendering issues

**Comment by pdpinch** [comment]
fixed a link in the description

**Comment by pdpinch** [comment]
The example from InVision is based on a page where the content is missing due to mitodl/ocw-data-parser#21

Here's an example from OCW Next where the data is already coming through, but the styling needs to be updated (as well as other issues:

before: https://ocw.mit.edu/courses/civil-and-environmental-engineering/1-74-land-water-food-and-climate-fall-2020/instructor-insights/

after: https://ocwnext.odl.mit.edu/courses/1-74-land-water-food-and-climate-fall-2020/sections/instructor-insights/

**Comment by gumaerc** [comment]
@pdpinch  Looking through my data, I only see 3 courses with pages that have a title of "This Course at MIT:"

```
18-354j-nonlinear-dynamics-ii-continuum-systems-spring-2015
18-409-algorithmic-aspects-of-machine-learning-spring-2015
21w-011-writing-and-rhetoric-rhetoric-and-contemporary-issues-fall-2015
```

Can we just change the titles on these pages in the original data, if these courses are still published?

**Comment by gumaerc** [comment]
@pdpinch @abdulkdawson In the markdown transformation, by default all sections are stacked vertically simply because there isn't really a way to apply formatting like that.  So, it would seem that we have already accomplished the 2nd task here, except in the design I noticed that there's a section with an instructor photo that's laid out like so:

![image](https://user-images.githubusercontent.com/12089658/105914358-3f1a0800-5ffc-11eb-9d61-8349e632eca6.png)

It seems that the picture and caption and the text are supposed to be laid out side by side, but there is no way to represent this in markdown , so it appears like this:

![image](https://user-images.githubusercontent.com/12089658/105914545-80121c80-5ffc-11eb-95bb-1bfe0ceefc92.png)

I could potentially look for image layouts like this and create a shortcode to present elements side by side like this, but it doesn't seem that this is a standardized layout used in OCW that would be easy to catch:

```
<div class="full alpha omega"><a name="insights"></a>
  <h2 class="title">Instructor Insights</h2>
  <div style="float: right; margin: -4px 0 auto 20px; padding: 0 0 0 20px; width: 375px; border-right: none;
    border-left: 1px solid #D5C9BA;">
    <p class="instruction"><img alt="Man in a blue shirt sounding outside a lab. The man has one arm positioned on
        his hip. He is smiling." src="./resolveuid/c91b44488e85cb8717b2cea9bb11dbd5" width="367" height="221" /><br />
      Patrick Winston, Ford Professor of Artificial Intelligence and Computer Science.
      (Photograph by Azeddine Tahiri. Used with permission.)</p>
  </div>
  <p>In the following pages, Professor Patrick Winston describes various aspects of how he teaches <em>6.034</em>
    <em>Artificial Intelligence</em>.</p>
  <ul>
    <li><a href="./resolveuid/eb66e88131e84c5dae78ba67407a1fc6">Teaching Heuristics</a> </li>
    <li><a href="./resolveuid/622ec6365134c39b7cca04a28496740f">Experiencing the Large Lecture as Theatre</a> </li>
  </ul>
  <p>Note: For additional insights from Professor Winston, please see &ldquo;<a
      href="http://web.mit.edu/fnl/volume/232/winston.html">Looking at the Numbers</a>&rdquo; in the MIT Faculty
    Newsletter.</p>
</div>
```
Moreover, it seems like the design has a content width of 956px, whereas up until now we have had a max content width of 795 px.  Is this something we should change theme-wide?  We will certainly need to if we want to display content side by side like that.

**Comment by pdpinch** [comment]
The OCW team is working on updating the Instructor Insights pages with incorrect page type. I'll ask them if they can also update the page titles to be consistent.

**Comment by abdulkdawson** [comment]
@gumaerc This is fine as it was a request from Sarah (OCW) to have this section stacked vertically anyway.

**Comment by abdulkdawson** [comment]
@pdpinch I'm updating the headers so they are consistent across all course pages. They will all follow the header styling of the course homepage.

**Comment by pdpinch** [comment]
@gumaerc what's the status of this issue?

**Comment by gumaerc** [comment]
@pdpinch There are 3 PR's that have been merged and are in the process of being released right now that solve the following issues:

 - Remove semester breakdown chart
 - Include text only from the pie chart breakdown keys

It looks as if I have a few more style tweaks to do as the design has changed a bit since the last time I checked.  @abdulkdawson can you verify that the invision link above is the most recent design?  Something else I noticed is that in the design, this thing is now red:

![image](https://user-images.githubusercontent.com/12089658/108908561-72e35000-75f1-11eb-8455-02407ef8da73.png)

The issue with this is that, that particular element is brought in from the legacy OCW site as an image:

https://open-learning-course-data-production.s3.amazonaws.com/6-034-artificial-intelligence-fall-2010/bb94a5ee3b0f0351808e14b34829d67a_300-approx.png

As you can see, the background is grey in the image.  We have a couple options on how we could approach making it red:

 - Replace these images at their origin
 - Catch them in `ocw-to-hugo` and rewrite new image URLs for them to new images
 - Catch them in `ocw-to-hugo` and rewrite the whole thing to be pure CSS

Also, I noticed that this content is side-by-side in the design but above we had mentioned that all elements will be vertically stacked.  This is how it currently renders:

![image](https://user-images.githubusercontent.com/12089658/108909113-24828100-75f2-11eb-82dc-2afc85306339.png)

It should be fairly straightforward to catch these images in `ocw-to-hugo` based on the `###-approx.png` pattern, but I'll need to do some checking to see if that is a consistent naming pattern for those images.  Anyway I'll put together a PR to get the style in line with the latest design as long as everything is kosher with the invision link above.
